import { parseArgs } from "@std/cli/parse-args";
import { createClient } from "./lib/dynamodb.js";

// const dynamo = createClient();

const allstars = [
  { slackID: "U0293EN5KPF", email: "vit.soural@flatzone.cz" },
  { slackID: "U029HDHPE8J", email: "tomas.netusil@netvor.co" },
  { slackID: "U029W65SCTS", email: "tomas.trnka@live.com" },
  { slackID: "U02C9JJP2SJ", email: "vojtech.uhlir@productboard.com" },
  { slackID: "U02C3C6GDFG", email: "jan.kahoun@heureka.cz" },
  { slackID: "U02AV7F591U", email: "jiri.fabian@topmonks.com" },
  { slackID: "U02C1NGPURH", email: "jan@apify.com" },
  { slackID: "U02BG1JAK6G", email: "annamarie.rybackova@applifting.cz" },
  { slackID: "U028RPER8H5", email: "lad.vasek@gmail.com" },
  { slackID: "U02CSM233N0", email: "sinacek@gmail.com" },
  { slackID: "U02AM81S4PR", email: "lukas.valenta@applifting.cz" },
  { slackID: "U02CUMJLJQN", email: "petr.mihle@gmail.com" },
  { slackID: "U0296F759JN", email: "linhart@flatzone.cz" },
  { slackID: "U02CKKMCLM8", email: "ondrej@liftago.com" },
  { slackID: "U0293ELJFQD", email: "martin.nedved@aimsapi.com" },
  { slackID: "U02AV7EN58W", email: "jirka.jansa@topmonks.com" },
  { slackID: "U0293EL9CJZ", email: "eva.hankusova@bizztreat.com" },
  { slackID: "U02AB696S77", email: "tomas.bachtik@novalia.cz" },
  { slackID: "U02AE77KAR0", email: "kristina.gerzova@novalia.cz" },
  { slackID: "U02C3C6EATY", email: "tomas.hylsky@heureka.cz" },
  { slackID: "U02D2MV63AL", email: "tomas.severyn@gmail.com" },
  { slackID: "U02DAR21FSP", email: "martin.ondas@bizmachine.com" },
  { slackID: "U02CJ2TU3B3", email: "milan.formanek@czechitas.cz" },
  { slackID: "U02AE77HK3L", email: "jakub.cisar@novalia.cz" },
  { slackID: "U0296F6NRH8", email: "petra.horackova@bizztreat.com" },
  { slackID: "U02CP28HDN1", email: "tomas.brukner@kiwi.com" },
  { slackID: "U02CCMDDTGQ", email: "petr@blabu.com" },
  { slackID: "U02C9JJKYVC", email: "jindrich@productboard.com" },
  { slackID: "U029PCEF64T", email: "ondrej.lanc@bizztreat.com" },
  { slackID: "U02CA2EB8RX", email: "petr.vnenk@applifting.cz" },
  { slackID: "U028ZNQ6PGE", email: "rdpanek@canarytrace.com" },
  { slackID: "U02AV7P2Y30", email: "filip.kirschner@applifting.cz" },
  { slackID: "U02D5PUDV33", email: "aadel.sykor@gmail.com" },
  { slackID: "U03SW8VTUDS", email: "barbora.hinnerova@clevermaps.io" },
  { slackID: "U029ALQN79U", email: "d.trzil@gmail.com" },
  { slackID: "U02CVJXS6NA", email: "jaroslav.faltus@gmail.com" },
  { slackID: "U03LRCHB673", email: "michal.taborsky@reflexcapital.com" },
  { slackID: "U0296F8DY2E", email: "thavryluk@gmail.com" },
  { slackID: "U02C1JXJTNK", email: "necas.jirik@gmail.com" }
];

const currentAttendees = [
  "U0296F6U42E",
  "U02CDP50M7A",
  "U02CSF7GZGS",
  "U01UZ3HLFHQ",
  "U03QU6KPR50",
  "U03P77QTE3U",
  "U05P9Q1F7M5",
  "U074KSPE3QU",
  "U02C9B43TPF",
  "U05MNE78NHL",
  "U05ASMRMVUN",
  "U02BGMRAZ8F",
  "U074FEVJJ4R",
  "U03SJP5SVTN",
  "U05PLH1QD46",
  "U05N4RTQTRV",
  "U0534309MNJ",
  "U05BDAPNBRP",
  "U03TL14C95K",
  "U05A8SA5WBB",
  "U0202S9SB1T",
  "U040FJTUQFQ",
  "U078ZRXQGES",
  "U01UVGVJ5BP",
  "U05QBC6UENN",
  "U07AHBKF14G",
  "U03MF1CRWKV",
  "U05K8UVQP7V",
  "U03T19RUVPS",
  "U073XTH138A",
  "U05APU7767L",
  "U028RPER8H5",
  "U05PF7YGVP1",
  "U02AV7ER72S",
  "U02D90QBD5F",
  "U07A78X1JQ1",
  "U040DTCJ7Q8",
  "U02CP2268Q2",
  "U02CSM233N0",
  "U0293ELFF8D",
  "U05LWMHU5T7",
  "U05A638G1GQ",
  "U040H01R0G1",
  "U03SVCU4KJM",
  "U05NLS27D6H",
  "U0773RTF6MS",
  "U01USTCS554",
  "U040GEG4T7T",
  "U0404KTHN5R",
  "U02AM81S4PR",
  "U02CJJ9M736",
  "U05N6AZKVHD",
  "U05PB7GUM70",
  "U05D6GR7JG5",
  "U05QZKNUUU9",
  "U040Y9VE932",
  "U059YRY66E7",
  "U03VA2HUM9R",
  "U03SBEHAL2F",
  "U075V4TE1QQ",
  "U01UVHTE877",
  "U040HNEBXFD",
  "U0293EL9CJZ",
  "U078L5L4NUA",
  "U0784TNT05C",
  "U05BP890X8B",
  "U05CBL519ED",
  "U05HEMKU78X",
  "U07858NA9N3",
  "U02C3C6EATY",
  "U079M6544PR",
  "U02D2MV63AL",
  "U075NRYRVD2",
  "U040TJ2SLAC",
  "U05BPAWJF99",
  "U073B2UP78F",
  "U0400GXA4KA",
  "U05Q4KW31MX",
  "U05NM13U86N",
  "U02CUP3D8GK",
  "U03TNAB52K0",
  "U074UF7CTUP",
  "U03SJKURZCN",
  "U03UY2U0RGB",
  "U05PNRJA4HY",
  "U072SGS8SRH",
  "U03SCS8GX8F",
  "U05MRPN9YBB",
  "U01VD5GGQ5C",
  "U02CJ2TU3B3",
  "U02CRRTDTV5",
  "U03SN5HQEF8",
  "U059KP1CGSH",
  "U0296F6NRH8",
  "U05BH02AFFT",
  "U03QXVAN0AH",
  "U02CCMDDTGQ",
  "U05Q17H2X6G",
  "U05K5MZLANM",
  "U05PA6E2XST",
  "U03ULP4LSAK",
  "U0205U8PZMG",
  "U03LRCHB673",
  "U02C9B40C6R",
  "U029PCEF64T",
  "U029ALQN79U",
  "U075SEZ6WPL",
  "U02B25T3VK5",
  "U0746EJHEQ7",
  "U03SHCHALNP",
  "U071CSFC78U",
  "U02B3RE7EQG",
  "U03USN3KKNW",
  "U0296F6RHNW",
  "U03VB8FV8MC",
  "U059M1XRKV5",
  "U02CA2EB8RX",
  "U0742GG9295",
  "U028ZNQ6PGE",
  "U05BZ9WNAJJ",
  "U040ER7K7R7",
  "U05D3DJGR6G",
  "U02AV7P2Y30"
];

function updateContact(key) {
  return dynamo.updateItem({
    TableName: "contacts",
    Key: key,
    UpdateExpression: "SET hasAllstarDiscount = :true",
    ExpressionAttributeValues: { ":true": true }
  });
}

async function* getAttendees(year) {
  const result = await dynamo.scan({
    TableName: "attendees",
    ProjectionExpression: "slackID, #name, company, events, image, ticketType",
    FilterExpression: "#y = :y",
    ExpressionAttributeNames: { "#y": "year", "#name": "name" },
    ExpressionAttributeValues: { ":y": year }
  });
  if (result.hasOwnProperty(Symbol.asyncIterator)) {
    for await (const page of result) {
      yield page.Items;
    }
  } else {
    yield result.Items;
  }
}

async function getAllAttendees() {
  const result = [];
  for await (const page of getAttendees(2024)) {
    result.push(...page);
  }
  return result;
}

function updateHackers() {
  return dynamo.updateItem({
    TableName: "attendees",
    ConditionExpression: "#year = :year AND ticketType = :hacker",
    UpdateExpression: "SET ticketPrice = :price",
    ExpressionAttributeNames: { "#year": "year" },
    ExpressionAttributeValues: { ":price": 6000, ":hacker": "hacker", ":year": 2024 }
  });
}

const attendees2024 = new Set([
  "anna.mai@czechitas.cz",
  "dita@czechitas.cz",
  "libor.vilimek@gmail.com",
  "rarous@gmail.com",
  "oodoow@gmail.com",
  "jakub.balada@gmail.com",
  "tomas@rokos.cz",
  "domino@dominikmichna.cz",
  "petr.kolinek@srovnejto.cz",
  "tomas.trnka@live.com",
  "lukas.navesnik@cesko.digital",
  "tomas@mavericks.legal",
  "zdenek.hesoun@happenee.com",
  "halikova.jani@seznam.cz",
  "petr.vaclavek@febventures.com",
  "katerina.lesch@gmail.com",
  "eva@peterka.cz",
  "lenka@hlidacstatu.cz",
  "martina.ivancikova@asahibeer.cz",
  "drbohlav.tomas@gmail.com",
  "bgorniakova@csas.cz",
  "dominik.dedicek@integritty.cz",
  "ludvik.anderle@gmail.com",
  "lucie.mairychova@czechitas.cz",
  "jakub.vraspir@merchantee.io",
  "krystof@krstf.com",
  "antonin.hackenberg@gmail.com",
  "tomasbuckley01@gmail.com",
  "s.vondrakova@gmail.com",
  "jan.bilek.osobni@gmail.com",
  "kroupa@kroupalide.cz",
  "barbora.hinnerova@clevermaps.io",
  "tadashicz@gmail.com",
  "vaclav@ostrozlik.cz",
  "tomas@capek.io",
  "doktor.ondrej@seznam.cz",
  "jan@apify.com",
  "tomas.mihle@gmail.com",
  "drobnik.j@gmail.com",
  "karel.simanek@bighub.cz",
  "alexander@saleshero.cz",
  "ir@izatlouk.cz",
  "kepka@kepi.name",
  "safmar84@gmail.com",
  "m@rketa.eu",
  "ondra@tichy.ws",
  "jiri.mouka@notum.cz",
  "jaroslav@mavericks.legal",
  "ales@roubicek.name",
  "ivan.kobr108@gmail.com",
  "marek@andrsk.cz",
  "lenka.niesigova@gmail.com",
  "tuckovaz@gmail.com",
  "michaela.mcclelland@javorina.com",
  "jana.zdvihalova@zazij-prpom.cz",
  "antonin.simersky@live.com",
  "petr@virtii.com",
  "zuzka.baladova@gmail.com",
  "hajekfila@gmail.com",
  "lenka.nawaisehova@gmail.com",
  "yen.kotara@gmail.com",
  "lucie.bezchlebova@gmail.com",
  "lad.vasek@gmail.com",
  "k.vorackova@gmail.com",
  "lukas@lukasbednarik.cz",
  "lucie.ottinger@cesko.digital",
  "karin.fuentesova@digitoo.cz",
  "daniel.hromada@hckr.studio",
  "hello@danielfranc.com",
  "filipsuk@gmail.com",
  "david.sanda@heureka.group",
  "bakor@seznam.cz",
  "prefix.duckling@mailbench.org",
  "m.kalkusova@gmail.com",
  "ondcej@gmail.com",
  "romana@romanavoriskova.cz",
  "elis@zazij-prpom.cz",
  "jakub@svejda-goldmann.cz",
  "kozuch.samuel@gmail.com",
  "sinacek@gmail.com",
  "jsem@radekduha.cz",
  "sehnoutkova@gmail.com",
  "horavamartin@gmail.com",
  "tkanak@seznam.cz",
  "kalab.frantisek@operatorict.cz",
  "petr@severa.name",
  "nikola.klouzkova@zazij-prpom.cz",
  "jan.misar@ackee.cz",
  "filip.drimalka@ef1.cz",
  "alanfridrich@gmail.com",
  "office@woodmaster.sk",
  "martin.horsky@email.cz",
  "rozalie.romanakova@cesko.digital",
  "goszler@raynet.cz",
  "pavla.verflova@czechitas.cz",
  "lada.nvk@gmail.com",
  "martin@section.cz",
  "pet.dvorakova@seznam.cz",
  "stadnyktetiana@gmail.com",
  "michaela@yyy.cz",
  "lukas.valenta@applifting.cz",
  "petra.fritsch@megumethod.com",
  "petr.panzner@gmail.com",
  "lustig.matyas@gmail.com",
  "kamila@lakmoos.com",
  "petr.mihle@gmail.com",
  "simon.podhajsky@gmail.com",
  "vesecky.adam@gmail.com",
  "jan@panoch.net",
  "filip@jirsak.org",
  "eli.janu.ska@gmail.com",
  "anezka@cesko.digital",
  "marekk.dduda@gmail.com",
  "jan.perla.jr@gmail.com",
  "martin.ukrop@gmail.com",
  "david@svejda-goldmann.cz",
  "jakub.siler@hicarl.cz",
  "zuzana.dobsickova@gmail.com",
  "katacek@gmail.com",
  "jirka.jansa@topmonks.com",
  "holbovap@gmail.com",
  "barnova.al@gmail.com",
  "eva.hankusova@bizztreat.com",
  "patrik.braborec@gmail.com",
  "katerina.vackova@loono.cz",
  "pavlina.vencovska@gmail.com",
  "martina.bekrova@gmail.com",
  "lom.denis@seznam.cz",
  "denisa@forendors.cz",
  "rybova.tereza@gmail.com",
  "anna.bohonek@gmail.com",
  "beatazemanova@email.cz",
  "ondra@zazij-prpom.cz",
  "doktor.tomas@seznam.cz",
  "kozlovska.juliee@gmail.com",
  "kubasmol@seznam.cz",
  "adamsobotka@duck.com",
  "adam@igloonet.cz",
  "radka.s@sedlakovalegal.com",
  "thylsky@gmail.com",
  "kfrancova07@gmail.com",
  "mike.maly@gmail.com",
  "david.cermak@prozeta.eu",
  "mitrofanovalana@gmail.com",
  "kl@skaut.cz",
  "zpelechova@gmail.com",
  "dupal.j@gmail.com",
  "tomas.severyn@gmail.com",
  "pavel.peroutka@gmail.com",
  "tomas.janda@jablotron.cz",
  "david@forendors.cz",
  "kozumplik@kroupalide.cz",
  "petr@joachim.cz",
  "matolin.matej@gmail.com",
  "fmach@fel.zcu.cz",
  "tomas@belada.net",
  "david@grudl.com",
  "martin.ondas@bizmachine.com",
  "tomas@netusil.com",
  "bohdan.blahovec@gmail.com",
  "quip@quip.cz",
  "marketa.trunkatova@apify.com",
  "ondrej.mekota@me.com",
  "klara.petovska@gmail.com",
  "jakub.nesetril@gmail.com",
  "johana.amlerova@carldatacompany.com",
  "info@jansterba.com",
  "filip.jediny@gmail.com",
  "mikrajic@gmail.com",
  "stepanka13@seznam.cz",
  "kaja.tesar@gmail.com",
  "pav.kosina@gmail.com",
  "milan.formanek@czechitas.cz",
  "terezatiller@gmail.com",
  "juraj.felix@cvcenter.cz",
  "jiri.pisa@topmonks.com",
  "jakub@reframecircle.cz",
  "hak.martin.hak@gmail.com",
  "magdaskodova7@gmail.com",
  "zdeeck@gmail.com",
  "petra.horackova@gmail.com",
  "dnsksr@gmail.com",
  "tomas.brukner@gmail.com",
  "filip.macek@heureka.group",
  "expres1666@gmail.com",
  "petr@budeto.xyz",
  "mjurik@fel.zcu.cz",
  "jan.soubusta@gooddata.com",
  "lukas.s@sedlakovalegal.com",
  "honza@kucharovi.cz",
  "elnazavr@gmail.com",
  "andrea@marter.cz",
  "tereza.fukatkova@gmail.com",
  "jirka@fenekpr.cz",
  "klara.palkoskova@zazij-prpom.cz",
  "michal.taborsky@reflexcapital.com",
  "aadel.sykor@gmail.com",
  "michal@michalblaha.cz",
  "ondrej.h@sedlakovalegal.com",
  "tomas@vortexcloud.io",
  "honza@husta.cz",
  "ondrej.lanc@gmail.com",
  "marek.morvai@gmail.com",
  "d.trzil@gmail.com",
  "adam@influencer.cz",
  "trentgwpersonal@gmail.com",
  "veronika.hallerova@gmail.com",
  "yurii.bliuchak@heureka.cz",
  "pe.stehlik@gmail.com",
  "palenicek@kroupalide.cz",
  "vena.kubik@seznam.cz",
  "riki@fczbkk.com",
  "pavel.geiger@jablotron.cz",
  "dalibor.pulkert@outboxers.com",
  "ivetakaucka@gmail.com",
  "y.dominik.polak@gmail.com",
  "af.kretschmer@gmail.com",
  "pavel@roivenue.com",
  "alice.navratilovaa@gmail.com",
  "daniel.weiss@jablotron.cz",
  "robert.krejca@javorina.com",
  "vojtech.matousek@carldatacompany.com",
  "petr.vnenk@applifting.cz",
  "mail@janhalama.cz",
  "lameorc@gmail.com",
  "andrea.hurychova@gmail.com",
  "pavel.trnka@hckr.studio",
  "rdpanek@canarytrace.com",
  "daria.hvizdalova@gmail.com",
  "valek.josef@seznam.cz",
  "petr@up.cz",
  "filip.kirschner@applifting.cz",
  "umlauf.filip@gmail.com",
  "adam@lepsinapad.cz",
  "ctibor.machala@gmail.com"
]);
const registrations2024 = new Set([
  "lustig.matyas@gmail.com",
  "atanasios.iliopulos@gmail.com",
  "mail@janhalama.cz",
  "vojtech.matousek@carldatacompany.com",
  "tomas.mihle@gmail.com",
  "sinacek@gmail.com",
  "drobnik.j@gmail.com",
  "zpelechova@gmail.com",
  "thylsky@gmail.com",
  "klara.palkoskova@zazij-prpom.cz",
  "martin.ondas@bizmachine.com",
  "stepanka13@seznam.cz",
  "ondrej.h@sedlakovalegal.com",
  "michal.taborsky@reflexcapital.com",
  "petr.vaclavek@febventures.com",
  "vena.kubik@seznam.cz",
  "tomas.janda@jablotron.cz",
  "ondrej.lanc@gmail.com",
  "tomas@capek.io",
  "filipsuk@gmail.com",
  "petr.mihle@gmail.com",
  "jakub.vraspir@merchantee.io",
  "sehnoutkova@gmail.com",
  "kalab.frantisek@operatorict.cz",
  "jan.soubusta@gooddata.com",
  "rdpanek@canarytrace.com",
  "lad.vasek@gmail.com",
  "ivetakaucka@gmail.com",
  "michaela@yyy.cz",
  "martin.horsky@email.cz",
  "johana.amlerova@carldatacompany.com",
  "adam@igloonet.cz",
  "andrea.hurychova@gmail.com",
  "umlauf.filip@gmail.com",
  "dupal.j@gmail.com",
  "palenicek@kroupalide.cz",
  "zuzka.baladova@gmail.com",
  "prefix.duckling@mailbench.org",
  "filip.jediny@gmail.com",
  "jan.perla.jr@gmail.com",
  "radka.s@sedlakovalegal.com",
  "eva.hankusova@bizztreat.com",
  "daniel.hromada@hckr.studio",
  "martin@section.cz",
  "kozuch.samuel@gmail.com",
  "mikrajic@gmail.com",
  "y.dominik.polak@gmail.com",
  "petr@up.cz",
  "doktor.ondrej@seznam.cz",
  "mike.maly@gmail.com",
  "tomas.severyn@gmail.com",
  "tuckovaz@gmail.com",
  "jakub@reframecircle.cz",
  "terezatiller@gmail.com",
  "nikola.klouzkova@zazij-prpom.cz",
  "d.trzil@gmail.com",
  "honza@husta.cz",
  "ondra@zazij-prpom.cz",
  "goszler@raynet.cz",
  "office@woodmaster.sk",
  "jsem@radekduha.cz",
  "beatazemanova@email.cz",
  "klara.petovska@gmail.com",
  "ondra@tichy.ws",
  "antonin.hackenberg@gmail.com",
  "hajekfila@gmail.com",
  "pokstefl.b@gmail.com",
  "jan@panoch.net",
  "zuzana.dobsickova@gmail.com",
  "david.sanda@heureka.group",
  "david@grudl.com",
  "anna.bohonek@gmail.com",
  "daniel.rutkovsky@megumethod.com",
  "ivan.kobr108@gmail.com",
  "vesecky.adam@gmail.com",
  "necron.cz@seznam.cz",
  "katerina.vackova@loono.cz",
  "elis@zazij-prpom.cz",
  "rybova.tereza@gmail.com",
  "matolin.matej@gmail.com",
  "tomas.trnka@live.com",
  "m@rketa.eu",
  "art.tokarevskikh@gmail.com",
  "pavel.geiger@jablotron.cz",
  "jaroslav@mavericks.legal",
  "magdaskodova7@gmail.com",
  "jakub.siler@hicarl.cz",
  "tkanak@seznam.cz",
  "lukas.navesnik@cesko.digital",
  "karel.simanek@bighub.cz",
  "yurii.bliuchak@heureka.cz",
  "simon.podhajsky@gmail.com",
  "ondcej@gmail.com",
  "tereza.fukatkova@gmail.com",
  "pe.stehlik@gmail.com",
  "jan.misar@ackee.cz",
  "lom.denis@seznam.cz",
  "hello@danielfranc.com",
  "kubasmol@seznam.cz",
  "petra.horackova@gmail.com",
  "daria.hvizdalova@gmail.com",
  "pavel@roivenue.com",
  "petr.panzner@gmail.com",
  "marek.hradil@faceup.com",
  "denisa@forendors.cz",
  "kozumplik@kroupalide.cz",
  "filip.kirschner@applifting.cz",
  "jakub@svejda-goldmann.cz",
  "safmar84@gmail.com",
  "riki@fczbkk.com",
  "tomas@netusil.com",
  "fmach@fel.zcu.cz",
  "libor.vilimek@gmail.com",
  "petr@joachim.cz",
  "petr@virtii.com",
  "martina.bekrova@gmail.com",
  "lada.nvk@gmail.com",
  "jakub.nesetril@gmail.com",
  "studio@dododobrik.sk",
  "eva@peterka.cz",
  "vaclav@ostrozlik.cz",
  "filip.macek@heureka.group",
  "jiri.mouka@notum.cz",
  "trentgwpersonal@gmail.com",
  "elnazavr@gmail.com",
  "petr@remembership.cz",
  "alice.navratilovaa@gmail.com",
  "kfrancova07@gmail.com",
  "halikova.jani@seznam.cz",
  "veronika.hallerova@gmail.com",
  "romana@romanavoriskova.cz",
  "petra.fritsch@megumethod.com",
  "ondrej@zazij-prpom.cz",
  "zdenek.hesoun@happenee.com",
  "zuzana.peskova@faceup.com",
  "marketa.trunkatova@apify.com",
  "jan@apify.com",
  "rozalie.romanakova@cesko.digital",
  "martin.ukrop@gmail.com",
  "patrik.diamant@nobar.cz",
  "vojta.d@slideslive.com",
  "adamsobotka@duck.com",
  "pavel.peroutka@gmail.com",
  "robert.krejca@javorina.com",
  "jan.bilek.osobni@gmail.com",
  "zdeeck@gmail.com",
  "mjurik@fel.zcu.cz",
  "honza@kucharovi.cz",
  "lucie.bezchlebova@gmail.com",
  "patrik.braborec@gmail.com",
  "lukas.s@sedlakovalegal.com",
  "trnkapavel@gmail.com",
  "bakor@seznam.cz",
  "jiri.ibl@me.com",
  "michal@michalblaha.cz",
  "krystof@krstf.com",
  "milan.formanek@czechitas.cz",
  "david@svejda-goldmann.cz",
  "s.vondrakova@gmail.com",
  "jan.kabat@bighub.cz",
  "juraj.felix@cvcenter.cz",
  "holbovap@gmail.com",
  "alexander@saleshero.cz",
  "jirka.jansa@topmonks.com",
  "petr.kolinek@srovnejto.cz",
  "lenka@hlidacstatu.cz",
  "domino@dominikmichna.cz",
  "tomas@vortexcloud.io",
  "m.kalkusova@gmail.com",
  "david@forendors.cz",
  "yen.kotara@gmail.com",
  "pavla.sinecka@gmail.com",
  "alanfridrich@gmail.com",
  "jiri.pisa@topmonks.com",
  "adam@influencer.cz",
  "mitrofanovalana@gmail.com",
  "dalibor.pulkert@outboxers.com",
  "info@jansterba.com",
  "eli.janu.ska@gmail.com",
  "tomas@mavericks.legal",
  "kozlovska.juliee@gmail.com",
  "lucie.ottinger@cesko.digital",
  "michaela.mcclelland@javorina.com",
  "tadashicz@gmail.com",
  "barnova.al@gmail.com",
  "petr.vnenk@applifting.cz",
  "ctibor.machala@gmail.com",
  "pavlina.vencovska@gmail.com",
  "horavamartin@gmail.com",
  "k.vorackova@gmail.com",
  "chocho@keboola.com",
  "oodoow@gmail.com",
  "david.cermak@prozeta.eu",
  "filip.drimalka@ef1.cz",
  "anezka@cesko.digital",
  "bgorniakova@csas.cz",
  "sju.catova@seznam.cz",
  "katerina.lesch@gmail.com",
  "anna.mai@czechitas.cz",
  "aadel.sykor@gmail.com",
  "tomasbuckley01@gmail.com",
  "dita@czechitas.cz",
  "barbora.hinnerova@clevermaps.io",
  "jana.zdvihalova@zazij-prpom.cz",
  "hak.martin.hak@gmail.com",
  "lenka.niesigova@gmail.com",
  "lukas.valenta@applifting.cz",
  "pet.dvorakova@seznam.cz",
  "karin.fuentesova@digitoo.cz",
  "lukas@lukasbednarik.cz",
  "tomas@rokos.cz",
  "quip@quip.cz",
  "marek@andrsk.cz",
  "valek.josef@seznam.cz",
  "martina.ivancikova@asahibeer.cz",
  "marek.morvai@gmail.com",
  "lameorc@gmail.com",
  "betty@zazij-prpom.cz",
  "petr@budeto.xyz",
  "expres1666@gmail.com",
  "marekk.dduda@gmail.com",
  "kaja.tesar@gmail.com",
  "tomas@belada.net",
  "kepka@kepi.name",
  "jan@lakmoos.com",
  "tomas.brukner@gmail.com",
  "daniel.weiss@jablotron.cz",
  "lucie.mairychova@czechitas.cz",
  "petr@severa.name",
  "drbohlav.tomas@gmail.com",
  "lenka.nawaisehova@gmail.com",
  "dominik.dedicek@integritty.cz",
  "kroupa@kroupalide.cz",
  "kl@skaut.cz",
  "adam@lepsinapad.cz",
  "kamila@lakmoos.com",
  "antonin.simersky@live.com",
  "lukas.kubica@pixxla.sk",
  "ondrej.mekota@me.com",
  "doktor.tomas@seznam.cz",
  "filip@jirsak.org",
  "stadnyktetiana@gmail.com",
  "af.kretschmer@gmail.com",
  "andrea@marter.cz",
  "hello@matejkristek.cz"
]);

async function main({}) {
  // const resp = await getAllAttendees();
  // console.dir(JSON.stringify(Array.from(resp).map(x => x.slackID)));

  const a = attendees2024;
  const b = registrations2024;
  console.dir(b.difference(a));
}

await main(parseArgs(process.argv.slice(2)));

// AWS_PROFILE=hackercamp node --permission --allow-net --allow-fs-read=../ --allow-fs-read=$HOME/.aws/credentials --allow-fs-read=$HOME/.aws/config adhoc.js --year=2026
