config:
  cloudflare-pages:compatibility-date: "2026-09-01"
  hackercamp:algolia-attendees-index-name: hc-attendees
  hackercamp:algolia-registrations-index-name: hc-registrations
  hackercamp:api-domain: api.hackercamp.cz
  hackercamp:aws-access-key-id: AKIAXAAHYX5INGZUDN7Y
  hackercamp:domain: hackercamp.cz
  hackercamp:donut-domain: donut.hackercamp.cz
  hackercamp:fakturoid-client-id: 0c56913e623e9e3aca9d7f4e93381b9283f5b574
  hackercamp:fakturoid-client-secret:
    secure: AAABAPF3dXdFHC2cn3M2ZWMPL+E9isx8OzB7ZbhbToOZmii8XIAuWIgVGEBGxGud65uiympQrdQrNgERKuqP9vaNgbaWNmTR
  hackercamp:fakturoid-webhook-token:
    secure: AAABAC2y0+KPnVrs8PNrWEkp0ytfAbj0bon6HXIVRctgJJsEuoiAFKLUwaTRgd8UENvcfhw4jIhuzpNG3e/Xa6LRPrBk7lIiVnj6nVch1zt89si3ScRWVwH3XYsWkCJE76nVv5YpV3nnRtBdAcX2eQ==
  hackercamp:google-calendar-program-id: c_afd9546ec33f93662ac0338da6d23a6b7daa6b5a1cc181afabaf6a8b11691b3a@group.calendar.google.com
  hackercamp:postmark-webhook-token:
    secure: AAABAC7xWGnAjPQWfgJOAVN6YcRB89HWc9sDFa3oC2V/PdezbM1W8lbzri3h+wiTxHzy5I5CdvpMu+9yY1PrEA==
  hackercamp:private-key:
    secure: AAABALEi/CWh7glkyY7gDR/2P+FpQX56VWoMLpSM0UuOR7rvfME1myIWxtewIPC8P8flBw2ORaushAWR2lGJfeBFKWiAjJFqpJYVLg6BuvQ=
  hackercamp:slack-announcement-channel: C026KB0G8V8
  hackercamp:slack-bot-token:
    secure: AAABAPVKNBH+3caqm5hEgc2T0CgPxs5CJc4gkWRDYtcLBlPPny2aJc2bDVdtNk2zbxWUTks8m5n4CN+XcmTkd+y/wlrJtIS25/aqZTMLo4uvc1uFCFFtEd4=
  hackercamp:web-domain: www.hackercamp.cz
  hackercamp:year: "2026"
  hackercamp:start-date: "20270902"
  hackercamp:end-date: "20270905"
  hackercamp:google-api-key:
    secure: AAABAFoqfAzlH7/6PKtRAd9YkdKTq6nh8TAxvRiE+gvxZVnQgjIODABcM45H7qXA07VYG4u012kXc+woVf5XduGPIZdANWc=
  hackercamp:nfctron-event-id: f39e0e21-be1d-4499-b92a-d0c38e45698b
  hackercamp:nfctron-bearer-token:
    secure: AAABAFx16G0z0lsL/vfwW0TJm4OEa/dh82VwUD8dV28XYwPaLQGfHGO9DZfiznnvP/+TtMzzS5dnt4G86V7dfN4e7I+PzwshZaCBB50O/3+t8T8k5QDdFJWSu9eNrbE0do/MAjZuDpDEzNhFqNJMbzJSGjKQ/tMfGbI23lKj5yFKuQHEd+FjD1faEyHe0IDEyjpTDY8JvMShSx+NgGjnI+gNf3hwbD91l4y8oHuhKme/20UVlgSw7thhraB72bmyIGpKnMFywKRnJuZLf1JdyNPynD7rqlW+ZGEdiX6kqxBVsN0R0jYeD0YQAPzBGZRURvui4wpLDzvhkj4k9Dprtg==
  hackercamp:slack-webhook-token:
    secure: AAABACy3bzpru9OxLE7eeHaoElan2qEwiBfpB+Q8UPzkON2oIC0vInjyQJGXVItq7MfVWyVm7CKwv8+1k55PN1jlsbCDwR/B0ZU=
  hackercamp:aws-secret-access-key:
    secure: AAABAB8a1howilYSZAMJBkh06lef2UYZu80eUhXHklsKn6yx+TrI1O3LvgSJNYeZBSRNEGeGd3IqM3lqs9ujGryBUBQnS7hc
  hackercamp:nfc-bearer-token:
    secure: AAABADRb1v7/ru1EQNEr2AqTYhZ6/CF1G8/DnAsVOr4uf/v4Knd1dczm1AnWRBqCpInavIhSrA2CSOe4/Liq7atKIlGN3iXLQK4S2MEpGUIv6UwTNkccSUZxgAu2pCCxTZ1kbJkHeTyeKT0C8ISjAEQK+x6xrn4RceHXYn5850ky/hmGJTL7e2F82bv0nK0QgRm9KDAKLWkeeoCI/dbqms/71jJDlkuS1DNsYI19cqqqIcelxwP96J3B3uQtt+7V/DFkq/mMi8PTSgdFmnJJNQLgZKC5Pefg7K9ivRSR6fEHPVMizqpztMjKwSojxfr/ubUlxeaEJxPRkHzzuqwWmA==
environment:
  - hackercamp-algolia
  - hackercamp-aws
  - hackercamp-postmark
  - hackercamp-rollbar
  - hackercamp-slack
  - rarous-cloudflare
