config:
  aws:region: eu-central-1
  hackercamp:algolia-admin-key:
    secure: AAABAA4XNdpHjMZ20VgptK68AwCpeF6ODv8IvQL4L7fLpZvRJkEDFk3g8+g7hNZ1Gh8rnRN6cgUc6tJuQejI1w==
  hackercamp:algolia-app-id: J77BFM3PLE
  hackercamp:algolia-attendees-index-name: hc-attendees
  hackercamp:algolia-registrations-index-name: hc-registrations
  hackercamp:algolia-search-key:
    secure: AAABAHscEyAGxDlFeEALF4xcitOWcrr5do2A79y4O0lDekbIa5jNQJX/qo89o2Yx1/iEVxewaVc4n4twoNfA4Q==
  hackercamp:api-domain: api.hackercamp.cz
  hackercamp:domain: hackercamp.cz
  hackercamp:donut-domain: donut.hackercamp.cz
  hackercamp:fakturoid-token:
    secure: AAABAO1IpF1r9MJvs/PAxvTotqlXlsg4dbWJsk5/51fWJCysxaDpWLoXNBerDjZTjBRQJGTAXszyFKJoKViR+KHz8Ywa/fNH
  hackercamp:fakturoid-webhook-token:
    secure: AAABABtVCcrrfoNz5vMiKPyHEEpSYXXOmrrT8DsT/c8aeJMocuIQ0GPjJOMYf+Ffd5eoSeAcOpkbQtVIjNw44vy60YYlNKYQaRxs9gKwubldaK13ircdx+/6TLIkIm7ok8fnv7NqrzTJj/LeF/vU3g==
  hackercamp:postmark-token:
    secure: AAABAF/Uwb6BOz5Iik1PbYzp+nvMR+VvkJw1T9l3V84G5htqzIgzTkDtA98Th9o1hB96Eg6rCrsmz5pXGx2ex0lo7NM=
  hackercamp:postmark-webhook-token:
    secure: AAABALwlpz9yqA5f4xNKXvTLVdQkaxyb6CCUIKcp3o9ymx2182ssEwFiNFNYqbMcbLgN4BvUyYKL3fcy2tAsVg==
  hackercamp:private-key:
    secure: AAABAMiObrKrGCJNcaB9RdcBRl2shK6sfmHwYdEChCgqQy3dVOxeVIuH/zk2R4dGDbqq/LjS7ZVWWuiDoutiFxdmDyoR21q9VQtOiQg=
  hackercamp:rollbar-access-token:
    secure: AAABANsAX/V4CvRNpbPVveHuf8od+m3/6dItRVCei/OvG0o+7HPn30+p9iVN8tVvkMjpPsxW22c/uZeoVjNhEw==
  hackercamp:slack-bot-token:
    secure: AAABAOcd56GLMiyf3SikIIfQjmDs1jIUg1OLYz8IWudo4J821x2EOod9C2s7YwIVS+nXc02JvvqEx4p2m3+OpEE4NI3653umgcN1UADmM+aywmDop3hFOmM=
  hackercamp:slack-client-id: "1990816352820.3334586910531"
  hackercamp:slack-client-secret:
    secure: AAABAPOefxVCpWj0ILWHq9UKChjnqzVPwlwAm8auqjii5KzUfgdHI7dV386pv69MQYJO2VV5KuWucxwuOwM4+g==
  hackercamp:slack-incoming-webhook:
    secure: AAABAG1uYVw8jL3J7xW6vyH0foRT5MJJm9QSrs/weKRHwhapwDGssqRhG8fprdJszWJICn1nGEycpL8qCvbaxvtWuaOFG6uNg+nhdnx17/XLNC+L4MPwIH6GjQKr4i3eJL/V5Ts0oCw+WcxtQ/Pze0A=
  hackercamp:web-domain: www.hackercamp.cz
  hackercamp:year: "2023"
  postmark:server-api-token:
    secure: AAABAJ8bBjERlSzcam+1C/wz2ygdjl+MQDW+ROCzPq5CtZwnYicF+N6fdBZJj7NGRvOBfpesC9VqhhicB6PXH/rnRGg=
  pulumi:template: aws-typescript
